language: csharp
solution: e2.sln
install:
  - nuget restore e2.sln
  - nuget install NUnit.Runners -Version 3.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release e2.sln
  - mono ./testrunner/NUnit.Console.3.0.0/tools/nunit3-console.exe ./bin/e2.exe
