addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 0fef6f9c-4a2b-4675-99ca-b1722af2191a
cache:
  directories: [$HOME/protobuf]
install: [bash build/install-protobuf.sh]
jdk: [oraclejdk8]
language: java
script: [mvn install -DprotocExecutable="$HOME/protobuf/bin/protoc", ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-04 20:17:02.982302
