addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: ba49a0e6-43d0-497c-8509-1707e1fa18b4
cache:
  directories: [$HOME/protobuf]
install: [bash build/install-protobuf.sh]
jdk: [oraclejdk8]
language: java
script: [mvn install -DprotocExecutable="$HOME/protobuf/bin/protoc", ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-08 14:41:09.880702
