language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/protobuf

sudo: false

install:
  - bash build/install-protobuf.sh

script:
  - mvn install -DprotocExecutable="$HOME/protobuf/bin/protoc"